# Generated by Django 5.0.7 on 2024-07-14 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('class_id', models.PositiveSmallIntegerField()),
                ('class_course', models.CharField(max_length=20)),
                ('class_trainer', models.CharField(max_length=20)),
                ('class_days', models.PositiveSmallIntegerField()),
                ('academic_year', models.CharField(max_length=20)),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('class_enrollment', models.PositiveBigIntegerField()),
                ('room_number', models.PositiveSmallIntegerField()),
                ('class_windows', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
