# Generated by Django 5.0.7 on 2024-07-14 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=20)),
                ('course_code', models.PositiveSmallIntegerField()),
                ('course_term', models.CharField(max_length=10)),
                ('course_hours', models.PositiveSmallIntegerField()),
                ('exam_method', models.CharField(max_length=20)),
                ('course_department', models.CharField(max_length=20)),
                ('course_description', models.TextField()),
                ('course_instructor', models.CharField(max_length=20)),
                ('course_fees', models.PositiveBigIntegerField()),
                ('course_level', models.CharField(max_length=25)),
            ],
        ),
    ]
