# Generated by Django 5.0.7 on 2024-08-01 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
